import Foundation

/// Generates a Dockerfile + build context that installs features as root via `RUN install.sh`.
/// Used by FeaturesRunner before `container build` (native arm64 platform; no `--rosetta`).
public enum FeatureDockerfileGenerator {
    public struct BuildContext: Equatable, Sendable {
        public var contextDirectory: String
        public var dockerfilePath: String
        public var dockerfileContents: String

        public init(contextDirectory: String, dockerfilePath: String, dockerfileContents: String) {
            self.contextDirectory = contextDirectory
            self.dockerfilePath = dockerfilePath
            self.dockerfileContents = dockerfileContents
        }
    }

    /// Write context: `feature-<id>/…` package files + `Dockerfile`.
    /// Layer directory and `/tmp/adev-feature-<id>` names use a stable identity
    /// (metadata `id`, else last path segment of the admitted ref), sanitized
    /// for Dockerfile/Apple paths. Duplicate ids append `-<index>`.
    ///
    /// - Parameter baseUser: Base image OCI `USER` from a **successful** inspect (nil/empty → restore `root`).
    ///   Callers MUST fail closed on inspect failure before invoking this — do not pass a fabricated user.
    public static func write(
        baseImage: String,
        ordered: [FeatureOrder.OrderedFeature],
        packages: [FetchedFeaturePackage],
        contextDirectory: String,
        remoteUser: String? = nil,
        containerUser: String? = nil,
        baseUser: String? = nil,
        contributions: FeatureContributions? = nil,
        fileManager: FileManager = .default
    ) throws -> BuildContext {
        try fileManager.createDirectory(atPath: contextDirectory, withIntermediateDirectories: true)

        // Map ref → package
        var byRef: [String: FetchedFeaturePackage] = [:]
        for p in packages {
            byRef[p.reference] = p
        }

        let userInstallEnv = FeatureOptions.userInstallEnvironment(
            remoteUser: remoteUser,
            containerUser: containerUser,
            baseUser: baseUser
        )

        var lines: [String] = []
        lines.append("# Generated by adevcontainer Features runner — do not edit")
        lines.append("FROM \(baseImage)")
        lines.append("")

        let layerNames = layerDirectoryNames(for: ordered)
        for (index, feature) in ordered.enumerated() {
            guard let pkg = byRef[feature.admitted.reference] else {
                throw CLIError(
                    code: CLIErrorCode.featureFetch,
                    property: "features",
                    message: "Internal: missing fetched package for \(feature.admitted.reference)"
                )
            }
            let featureDirName = layerNames[index]
            let destFeatureDir = (contextDirectory as NSString).appendingPathComponent(featureDirName)
            let containerPath = "/tmp/adev-\(featureDirName)"
            try? fileManager.removeItem(atPath: destFeatureDir)
            try copyPackage(from: pkg.directoryPath, to: destFeatureDir, fileManager: fileManager)

            // Feature metadata containerEnv → Dockerfile ENV before install RUN so
            // BuildKit expands $PATH/$VAR (parity with @devcontainers/cli). Do not
            // put these through installEnvExportPrefix (shell single-quotes wipe PATH).
            // Options + _REMOTE_*/_CONTAINER_* stay on the RUN export prefix and win
            // over ENV for the install process on key collision.
            var installEnv = FeatureOptions.installEnvironment(
                user: feature.admitted.options,
                defaults: feature.metadata.optionDefaults
            )
            for (k, v) in userInstallEnv {
                installEnv[k] = v
            }
            let exportPrefix = FeatureOptions.installEnvExportPrefix(installEnv)
            let envLines = FeatureOptions.dockerfileEnvLines(feature.metadata.containerEnv)

            lines.append("# Feature: \(feature.admitted.reference)")
            lines.append("USER root")
            lines.append("COPY \(featureDirName) \(containerPath)")
            for envLine in envLines {
                lines.append(envLine)
            }
            // Match @devcontainers/cli: chmod -R 0755 the package before install so
            // lifecycle scripts (e.g. shell-history oncreate.sh) remain executable when
            // install.sh copies them into /usr/local/share/… for bare-path shell hooks.
            // (sh -lc /path/script requires +x; OCI layers often ship scripts as 0644.)
            lines.append(
                "RUN chmod -R 0755 \(containerPath) "
                    + "&& cd \(containerPath) "
                    + "&& \(exportPrefix)./install.sh "
                    + "&& rm -rf \(containerPath)"
            )
            lines.append("")
        }

        // Restore base image default user after root install layers (empty OCI USER → root).
        let restoreUser = RemoteUserResolution.nonEmptyTrimmed(baseUser) ?? "root"
        lines.append("# Restore base image USER (install layers run as root)")
        lines.append("USER \(restoreUser)")
        lines.append("")

        // Persist unioned lifecycle hooks (base-image metadata + features) so resume remelt
        // does not require a Features rebuild and does not drop base-image fragments.
        let baked = contributions ?? (try? FeatureContributionMerge.collect(from: ordered))
        if let baked, let json = DevContainerMetadataLabel.encodeFragments(baked) {
            lines.append("LABEL \(DevContainerMetadataLabel.labelKey)=\(dockerfileLabelValue(json))")
            lines.append("")
        }

        let contents = lines.joined(separator: "\n")
        let dockerfilePath = (contextDirectory as NSString).appendingPathComponent("Dockerfile")
        try contents.write(toFile: dockerfilePath, atomically: true, encoding: .utf8)

        return BuildContext(
            contextDirectory: contextDirectory,
            dockerfilePath: dockerfilePath,
            dockerfileContents: contents
        )
    }

    /// Dockerfile-safe context directory per ordered feature (`feature-<id>`).
    /// Prefer metadata `id`; else last path segment of the admitted reference.
    /// Duplicate slugs append `-<index>` so COPY/RUN paths stay unique.
    public static func layerDirectoryNames(for ordered: [FeatureOrder.OrderedFeature]) -> [String] {
        var used: Set<String> = []
        var names: [String] = []
        names.reserveCapacity(ordered.count)
        for (index, feature) in ordered.enumerated() {
            let slug = sanitizeLayerSlug(rawLayerIdentity(for: feature))
            var name = "feature-\(slug)"
            if used.contains(name) {
                name = "feature-\(slug)-\(index)"
            }
            var suffix = 2
            while used.contains(name) {
                name = "feature-\(slug)-\(index)-\(suffix)"
                suffix += 1
            }
            used.insert(name)
            names.append(name)
        }
        return names
    }

    /// Stable human identity before path sanitizing.
    static func rawLayerIdentity(for feature: FeatureOrder.OrderedFeature) -> String {
        let id = feature.metadata.id.trimmingCharacters(in: .whitespacesAndNewlines)
        if !id.isEmpty { return id }
        return FeatureRef.featureId(from: feature.admitted.reference)
    }

    /// Dockerfile + Apple-ref-safe slug: no `/` or `:`, `[a-z0-9._-]` only.
    static func sanitizeLayerSlug(_ raw: String) -> String {
        let mapped = raw.lowercased().unicodeScalars.map { scalar -> Character in
            if CharacterSet.alphanumerics.contains(scalar)
                || scalar == "." || scalar == "_" || scalar == "-"
            {
                return Character(scalar)
            }
            return "-"
        }
        var name = String(mapped)
        while name.contains("--") {
            name = name.replacingOccurrences(of: "--", with: "-")
        }
        name = name.trimmingCharacters(in: CharacterSet(charactersIn: "-."))
        if name.count > 48 {
            name = String(name.prefix(48)).trimmingCharacters(in: CharacterSet(charactersIn: "-."))
        }
        return name.isEmpty ? "feature" : name
    }

    /// Dockerfile `LABEL` value: double-quoted, with `\`, `"`, and `$` escaped.
    private static func dockerfileLabelValue(_ raw: String) -> String {
        let escaped = raw
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "$", with: "\\$")
        return "\"\(escaped)\""
    }

    private static func copyPackage(from source: String, to dest: String, fileManager: FileManager) throws {
        try fileManager.createDirectory(atPath: dest, withIntermediateDirectories: true)
        let contents = try fileManager.contentsOfDirectory(atPath: source)
        for name in contents {
            if name.hasPrefix(".") { continue }
            let from = (source as NSString).appendingPathComponent(name)
            let to = (dest as NSString).appendingPathComponent(name)
            if fileManager.fileExists(atPath: to) {
                try fileManager.removeItem(atPath: to)
            }
            try fileManager.copyItem(atPath: from, toPath: to)
        }
        // Ensure install.sh exists
        let install = (dest as NSString).appendingPathComponent("install.sh")
        guard fileManager.fileExists(atPath: install) else {
            throw CLIError(
                code: CLIErrorCode.featureMetadata,
                property: "features",
                message: "Feature package at \(source) is missing install.sh",
                hint: "Each feature artifact must include install.sh"
            )
        }
    }
}
