import Foundation

/// Generates a Dockerfile + build context that installs features as root via `RUN install.sh`.
/// Used by FeaturesRunner before `container build` (native arm64 platform; no `--rosetta`).
public enum FeatureDockerfileGenerator {
    public struct BuildContext: Equatable, Sendable {
        public var contextDirectory: String
        public var dockerfilePath: String
        public var dockerfileContents: String

        public init(contextDirectory: String, dockerfilePath: String, dockerfileContents: String) {
            self.contextDirectory = contextDirectory
            self.dockerfilePath = dockerfilePath
            self.dockerfileContents = dockerfileContents
        }
    }

    /// Write context: `features/<index>/…` package files + `Dockerfile`.
    public static func write(
        baseImage: String,
        ordered: [FeatureOrder.OrderedFeature],
        packages: [FetchedFeaturePackage],
        contextDirectory: String,
        remoteUser: String? = nil,
        containerUser: String? = nil,
        fileManager: FileManager = .default
    ) throws -> BuildContext {
        try fileManager.createDirectory(atPath: contextDirectory, withIntermediateDirectories: true)

        // Map ref → package
        var byRef: [String: FetchedFeaturePackage] = [:]
        for p in packages {
            byRef[p.reference] = p
        }

        let userInstallEnv = FeatureOptions.userInstallEnvironment(
            remoteUser: remoteUser,
            containerUser: containerUser
        )

        var lines: [String] = []
        lines.append("# Generated by adevcontainer Features runner — do not edit")
        lines.append("FROM \(baseImage)")
        lines.append("")

        for (index, feature) in ordered.enumerated() {
            guard let pkg = byRef[feature.admitted.reference] else {
                throw CLIError(
                    code: CLIErrorCode.featureFetch,
                    property: "features",
                    message: "Internal: missing fetched package for \(feature.admitted.reference)"
                )
            }
            let featureDirName = "feature-\(index)"
            let destFeatureDir = (contextDirectory as NSString).appendingPathComponent(featureDirName)
            try? fileManager.removeItem(atPath: destFeatureDir)
            try copyPackage(from: pkg.directoryPath, to: destFeatureDir, fileManager: fileManager)

            var installEnv = FeatureOptions.installEnvironment(
                user: feature.admitted.options,
                defaults: feature.metadata.optionDefaults
            )
            for (k, v) in userInstallEnv {
                installEnv[k] = v
            }
            let exportPrefix = FeatureOptions.installEnvExportPrefix(installEnv)

            lines.append("# Feature: \(feature.admitted.reference)")
            lines.append("USER root")
            lines.append("COPY \(featureDirName) /tmp/adev-feature-\(index)")
            // Match @devcontainers/cli: chmod -R 0755 the package before install so
            // lifecycle scripts (e.g. shell-history oncreate.sh) remain executable when
            // install.sh copies them into /usr/local/share/… for bare-path shell hooks.
            // (sh -lc /path/script requires +x; OCI layers often ship scripts as 0644.)
            lines.append(
                "RUN chmod -R 0755 /tmp/adev-feature-\(index) "
                    + "&& cd /tmp/adev-feature-\(index) "
                    + "&& \(exportPrefix)./install.sh "
                    + "&& rm -rf /tmp/adev-feature-\(index)"
            )
            lines.append("")
        }

        let contents = lines.joined(separator: "\n")
        let dockerfilePath = (contextDirectory as NSString).appendingPathComponent("Dockerfile")
        try contents.write(toFile: dockerfilePath, atomically: true, encoding: .utf8)

        return BuildContext(
            contextDirectory: contextDirectory,
            dockerfilePath: dockerfilePath,
            dockerfileContents: contents
        )
    }

    private static func copyPackage(from source: String, to dest: String, fileManager: FileManager) throws {
        try fileManager.createDirectory(atPath: dest, withIntermediateDirectories: true)
        let contents = try fileManager.contentsOfDirectory(atPath: source)
        for name in contents {
            if name.hasPrefix(".") { continue }
            let from = (source as NSString).appendingPathComponent(name)
            let to = (dest as NSString).appendingPathComponent(name)
            if fileManager.fileExists(atPath: to) {
                try fileManager.removeItem(atPath: to)
            }
            try fileManager.copyItem(atPath: from, toPath: to)
        }
        // Ensure install.sh exists
        let install = (dest as NSString).appendingPathComponent("install.sh")
        guard fileManager.fileExists(atPath: install) else {
            throw CLIError(
                code: CLIErrorCode.featureMetadata,
                property: "features",
                message: "Feature package at \(source) is missing install.sh",
                hint: "Each feature artifact must include install.sh"
            )
        }
    }
}
